### ISSUE TITLE
关于单读多写的实现机制

### ISSUE THREAD

**Issue by jswlives** [atframework/libatbus#11]
同机器之间的进程通信可以通过共享内存管道，想请教下这个单读多写队列的实现原理，网上看过的很多资料都是线程之间通过原子操作来实现，但是在进程之间，是怎么实现多个进程的同步写操作？

**Comment by owent** [comment]
请参考: https://owent.net/2014/1099.html
进程间是可以共享物理内存空间的（虚拟地址不同，单指向相同的物理内存页）。所以也可以通过原子操作来实现
