### ISSUE TITLE
使用 Windows + MinGW(msys2) 方式 编译报错 ？

### ISSUE THREAD

**Issue by zuowanbushiwo** [atframework/libatbus#2]
$ make
Scanning dependencies of target atframe_utils
[  3%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/algorithm/base64.cpp.obj
[  6%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/algorithm/crc.cpp.obj
[  9%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/algorithm/crypto_cipher.cpp.obj
[ 12%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/algorithm/crypto_dh.cpp.obj
[ 16%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/algorithm/murmur_hash.cpp.obj
[ 19%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/algorithm/xxtea.cpp.obj
[ 22%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/cli/cmd_option_list.cpp.obj
[ 25%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/cli/cmd_option_value.cpp.obj
[ 29%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/cli/shell_font.cpp.obj
[ 32%] Building CXX object deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/common/file_system.cpp.obj
E:/OpenSource/libatbus/3rd_party/atframe_utils/repo/src/common/file_system.cpp: In static member function 'static bool util::file_system::mkdir(const char*, bool, int)':
E:/OpenSource/libatbus/3rd_party/atframe_utils/repo/src/common/file_system.cpp:166:71: error: unused parameter 'mode' [-Werror=unused-parameter]
     bool file_system::mkdir(const char *dir_path, bool recursion, int mode) {
                                                                   ~~~~^~~~
cc1plus.exe: all warnings being treated as errors
make[2]: *** [deps/atframe_utils/CMakeFiles/atframe_utils.dir/build.make:180：deps/atframe_utils/CMakeFiles/atframe_utils.dir/src/common/file_system.cpp.obj] 错误 1
make[1]: *** [CMakeFiles/Makefile2:91：deps/atframe_utils/CMakeFiles/atframe_utils.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2

**Comment by owt5008137** [comment]
已修复。CI 上的编译器版本不是很高，没有检测到这个warning。
麻烦手动删除下 ```3rd_party/atframe_utils/repo``` 然后重新执行cmake后重试下。

参考命令:

```bash
cd <REPO DIR>;
if [ -e "3rd_party/atframe_utils/repo" ]; then
    rm -rf "3rd_party/atframe_utils/repo";
fi

chmod +x ./cmake_dev.sh;
./cmake_dev.sh -lus ;

cd build_mingw* ;

cmake --build . -- -j4 ;
```

**Comment by zuowanbushiwo** [comment]
感谢，已经很好的解决了！
