### ISSUE TITLE
ubuntu 20.04下 编译不通过

### ISSUE THREAD

**Issue by JackyLucifer** [atframework/libatbus#20]
cmake之后
直接make
提示内容如下，帮忙看一下
libatbus/atframework/atframe_utils/include/cli/cmd_option_bind_param_list.h:64:64: error: conversion from ‘long unsigned int’ to ‘int’ may change value [-Werror=conversion]
   64 | struct build_args_index : build_args_index<N - 1, _Index..., sizeof...(_Index)> {};

**Comment by owent** [comment]
感谢反馈，这个问题在上游依赖库，可能某些版本的GCC对模板和非模板类型处理不一样，我处理测试一下。跑完全部的CI检查可能会晚一些。可否提供一下 gcc版本？

**Comment by JackyLucifer** [comment]
test@test-AMD:~/lib/libatbus/build$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by JackyLucifer** [comment]
我编译atframe_utils时正常
编译atbus和atapp都出现同样问题

**Comment by JackyLucifer** [comment]
参照一下看看

**Comment by JackyLucifer** [comment]
好，我这就试试

**Comment by JackyLucifer** [comment]
还是一样的

**Comment by owent** [comment]
> 还是一样的

不好意思，前面push漏了。现在dev分支应该可以了

**Comment by owent** [comment]
> 我强行更新了atframework目录里面的atframe_utils 后能编译了，但是没有在_deps目录生成uuidgen
> 
> 出现以下错误 make[2]: *** 没有规则可制作目标“unwind-generic”，由“bin/uuidgen” 需求。 停止。

这个 libunwind 的查找修复是 atframework/cmake-toolset 这个子模块

**Comment by JackyLucifer** [comment]
好，我现在拉下来编译一下

**Comment by JackyLucifer** [comment]
还是提示这个
[ 52%] Building CXX object _deps/atframe_utils/tools/uuidgen/CMakeFiles/uuidgen.dir/uuidgen.cpp.o
make[2]: *** 没有规则可制作目标“unwind-generic”，由“bin/uuidgen” 需求。 停止。
make[1]: *** [CMakeFiles/Makefile2:239：_deps/atframe_utils/tools/uuidgen/CMakeFiles/uuidgen.dir/all] 错误 2
make: *** [Makefile:163：all] 错误 2

**Comment by JackyLucifer** [comment]
成了，不能设置LIBUNWIND_ENABLED为TRUE

**Comment by owent** [comment]
> 成了，不能设置LIBUNWIND_ENABLED为TRUE

不需要手动设置的，自动会检测的。

**Comment by JackyLucifer** [comment]
libatapp这个也有同样问题，也更新了吧

**Comment by owent** [comment]
> libatapp这个也有同样问题，也更新了吧

还没有，一会儿更新

**Comment by owent** [comment]
> libatapp这个也有同样问题，也更新了吧

Done, github下线老的gcc 4.8的环境了。我找了个新环境配置。
