### ISSUE TITLE
Windows + MSVC 可以使用vcpkg 配置吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [atframework/libatbus#3]
因为vs2017 调试功能很方便也很强大，很方便新手理解程序。
我在https://github.com/microsoft/vcpkg 发现已经有人移植好了libuv 和 msgpack，我也安装了，那怎么导入如这个工程？需要修改cmake 文件吗？

PS E:\OpenSource\vcpkg>  **.\vcpkg integrate install**
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=E:/OpenSource/vcpkg/scripts/buildsystems/vcpkg.cmake"
PS E:\OpenSource\vcpkg> **.\vcpkg.exe install libuv**
The following packages will be built and installed:
    libuv[core]:x86-windows
Starting package 1/1: libuv:x86-windows
Building package libuv[core]:x86-windows...
-- Downloading https://github.com/libuv/libuv/archive/v1.28.0.tar.gz...
-- Extracting source E:/OpenSource/vcpkg/downloads/libuv-libuv-v1.28.0.tar.gz
-- Using source at E:/OpenSource/vcpkg/buildtrees/libuv/src/v1.28.0-c436f63419
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libuv[core]:x86-windows... done
Installing package libuv[core]:x86-windows...
Installing package libuv[core]:x86-windows... done
Elapsed time for package libuv:x86-windows: 47.68 s

Total elapsed time: 47.68 s

The package libuv:x86-windows provides CMake targets:

    find_package(unofficial-libuv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::libuv::libuv)

PS E:\OpenSource\vcpkg> **.\vcpkg.exe install msgpack**
The following packages will be built and installed:
    msgpack[core]:x86-windows
Starting package 1/1: msgpack:x86-windows
Building package msgpack[core]:x86-windows...
-- Downloading https://github.com/msgpack/msgpack-c/archive/cpp-3.1.1.tar.gz...
-- Extracting source E:/OpenSource/vcpkg/downloads/msgpack-msgpack-c-cpp-3.1.1.tar.gz
-- Using source at E:/OpenSource/vcpkg/buildtrees/msgpack/src/cpp-3.1.1-eab3c56b41
-- Applying patch E:/OpenSource/vcpkg/ports/msgpack/add-static-lib-option.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package msgpack[core]:x86-windows... done
Installing package msgpack[core]:x86-windows...
Installing package msgpack[core]:x86-windows... done
Elapsed time for package msgpack:x86-windows: 46.6 s

Total elapsed time: 46.6 s

The package msgpack:x86-windows provides CMake targets:

    find_package(msgpack CONFIG REQUIRED)
    target_link_libraries(main PRIVATE msgpackc msgpackc-cxx)

PS E:\OpenSource\vcpkg>

**Comment by zuowanbushiwo** [comment]
我vs2017  编译报错，能麻烦帮忙看一下吗？
这个配置：
$ cmake  ..  -DCMAKE_TOOLCHAIN_FILE=E:/OpenSource/vcpkg/scripts/buildsystems/vcpkg.cmake  -DPROJECT_ENABLE_SAMPLE=ON  -DPROJECT_ENABLE_UNITTEST=ON  -DPROJECT_ENABLE_TOOLS=ON
-- Available Build Type: Debug;Release;MinSizeRel;RelWithDebInfo
-- MSVC 1916 found. using /std:c++17
-- Build Type: RelWithDebInfo
-- Dependency: Libuv prebuilt found.(E:/OpenSource/vcpkg/installed/x86-windows/debug/lib/libuv.lib)
-- Win32: custom add lib advapi32 iphlpapi psapi shell32 user32 userenv ws2_32
-- Dependency: Msgpack found.(E:/OpenSource/libatbus/3rd_party/msgpack/prebuilt//include)
-- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
-- Lua not found and disabled.
-- Stacktrace: LOG_STACKTRACE_USING_DBGHELP=1.
-- Libuv support enabled
-- Curl support enabled
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found version "1.1.1b")
-- Could NOT find MbedTLS (missing: MbedTLS_INCLUDE_DIRS MbedTLS_TLS_LIBRARIES)
-- Could NOT find Libsodium (missing: Libsodium_INCLUDE_DIRS Libsodium_LIBRARIES)
-- Configure E:/OpenSource/libatbus/3rd_party/atframe_utils/repo/test
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Configure E:/OpenSource/libatbus/src
-- Configure E:/OpenSource/libatbus/sample
-- Configure Unit Test E:/OpenSource/libatbus/test
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Configure Tools E:/OpenSource/libatbus/tools
-- Configuring done
-- Generating done
-- Build files have been written to: E:/OpenSource/libatbus/vs_build

配置完成后使用VS2017 编译，错误如下：

1>------ 已启动全部重新生成: 项目: ZERO_CHECK, 配置: Debug Win32 ------
1>Checking Build System
1>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/deps/atframe_utils/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/deps/atframe_utils/sample/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/deps/atframe_utils/test/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/src/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/sample/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/test/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/tools/CMakeFiles/generate.stamp is up-to-date.
2>------ 已启动全部重新生成: 项目: atbus, 配置: Debug Win32 ------
3>------ 已启动全部重新生成: 项目: atframe_utils, 配置: Debug Win32 ------
2>Building Custom Rule E:/OpenSource/libatbus/src/CMakeLists.txt
3>Building Custom Rule E:/OpenSource/libatbus/3rd_party/atframe_utils/repo/CMakeLists.txt
2>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/src/CMakeFiles/generate.stamp is up-to-date.
3>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/deps/atframe_utils/CMakeFiles/generate.stamp is up-to-date.
2>atbus_connection.cpp
2>atbus_endpoint.cpp
3>base64.cpp
2>atbus_msg_handler.cpp
2>atbus_node.cpp
3>crc.cpp
3>crypto_cipher.cpp
3>crypto_dh.cpp
3>murmur_hash.cpp
3>xxtea.cpp
3>cmd_option_list.cpp
3>cmd_option_value.cpp
3>shell_font.cpp
3>file_system.cpp
3>string_oprs.cpp
3>log_formatter.cpp
3>log_sink_file_backend.cpp
3>log_stacktrace.cpp
3>log_wrapper.cpp
3>lua_log_adaptor.cpp
3>http_content_type.cpp
3>http_request.cpp
3>tquerystring.cpp
3>time_utility.cpp
2>channel_io_stream.cpp
2>channel_mem.cpp
2>channel_shm.cpp
2>channel_utility.cpp
3>lua_log_adaptor.obj : warning LNK4221: 此对象文件未定义任何之前未定义的公共符号，因此任何耗用此库的链接操作都不会使用此文件
3>crypto_dh.obj : warning LNK4221: 此对象文件未定义任何之前未定义的公共符号，因此任何耗用此库的链接操作都不会使用此文件
3>crypto_cipher.obj : warning LNK4221: 此对象文件未定义任何之前未定义的公共符号，因此任何耗用此库的链接操作都不会使用此文件
3>atframe_utils.vcxproj -> E:\OpenSource\libatbus\vs_build\lib\Debug\atframe_utils.lib
3>已完成生成项目“atframe_utils.vcxproj”的操作。
4>------ 已启动全部重新生成: 项目: atframe_utils_sample, 配置: Debug Win32 ------
5>------ 已启动全部重新生成: 项目: atframe_utils_unit_test, 配置: Debug Win32 ------
4>Building Custom Rule E:/OpenSource/libatbus/3rd_party/atframe_utils/repo/sample/CMakeLists.txt
4>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/deps/atframe_utils/sample/CMakeFiles/generate.stamp is up-to-date.
4>cmd_option_main.cpp
4>sample.cpp
2>buffer.cpp
5>Building Custom Rule E:/OpenSource/libatbus/3rd_party/atframe_utils/repo/test/CMakeLists.txt
5>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/deps/atframe_utils/test/CMakeFiles/generate.stamp is up-to-date.
5>main.cpp
5>ac_automation_test.cpp
5>atomic_int_test.cpp
5>base64_test.cpp
5>crypto_cipher_test.cpp
5>crypto_dh_test.cpp
5>file_system_test.cpp
5>foreach_test.cpp
5>intrusive_ptr_test.cpp
5>lock_test.cpp
5>lru_object_pool_test.cpp
5>mixed_int_test.cpp
5>random_test.cpp
5>singleton_test.cpp
5>string_oprs_test.cpp
5>time_test.cpp
5>xxtea_test.cpp
5>test_case_base.cpp
4>atframe_utils_sample.vcxproj -> E:\OpenSource\libatbus\vs_build\deps\atframe_utils\sample\Debug\atframe_utils_sample.exe
5>test_manager.cpp
2>atbus.vcxproj -> E:\OpenSource\libatbus\vs_build\lib\Debug\atbus.lib
6>------ 已启动全部重新生成: 项目: atbus_sample_usage_01, 配置: Debug Win32 ------
7>------ 已启动全部重新生成: 项目: atbus_unit_test, 配置: Debug Win32 ------
8>------ 已启动全部重新生成: 项目: benchmark_io_stream_channel_recv, 配置: Debug Win32 ------
5>atframe_utils_unit_test.vcxproj -> E:\OpenSource\libatbus\vs_build\deps\atframe_utils\test\Debug\atframe_utils_unit_test.exe
9>------ 已启动全部重新生成: 项目: benchmark_io_stream_channel_send, 配置: Debug Win32 ------
7>Building Custom Rule E:/OpenSource/libatbus/test/CMakeLists.txt
7>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/test/CMakeFiles/generate.stamp is up-to-date.
6>Building Custom Rule E:/OpenSource/libatbus/sample/CMakeLists.txt
8>Building Custom Rule E:/OpenSource/libatbus/tools/CMakeLists.txt
9>Building Custom Rule E:/OpenSource/libatbus/tools/CMakeLists.txt
6>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/sample/CMakeFiles/generate.stamp is up-to-date.
8>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/tools/CMakeFiles/generate.stamp is up-to-date.
9>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/tools/CMakeFiles/generate.stamp is up-to-date.
8>benchmark_io_stream_channel_recv.cpp
9>benchmark_io_stream_channel_send.cpp
7>main.cpp
7>test_case_base.cpp
7>test_manager.cpp
7>atbus_endpoint_test.cpp
7>atbus_node_msg_test.cpp
7>atbus_node_nodesync_test.cpp
7>atbus_node_reg_test.cpp
6>sample_usage_01.cpp
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp : error C2220: 警告被视为错误 - 没有生成“object”文件
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
7>atbus_node_relationship_test.cpp
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(16): error C2065: “conf”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(21): error C2065: “ev_loop”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(48): error C2065: “conf”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(56): error C2065: “node2”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(56): error C3481: “recved”: 未找到 lambda 捕获变量
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(70): error C2065: “node1”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(70): error C2065: “node2”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(70): error C2065: “send_data”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(73): error C2065: “conf”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(77): error C2065: “node2”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(45): error C2043: 非法 break
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(83): error C2065: “ev_loop”: 未声明的标识符
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(83): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(83): error C2365: “uv_run”: 重定义；以前的定义是“函数”
6>E:\OpenSource\vcpkg\installed\x86-windows\include\uv.h(284): note: 参见“uv_run”的声明
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(84): error C2059: 语法错误:“}”
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(84): error C2143: 语法错误: 缺少“;”(在“}”的前面)
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(89): error C2059: 语法错误:“}”
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp(89): error C2143: 语法错误: 缺少“;”(在“}”的前面)
6>已完成生成项目“atbus_sample_usage_01.vcxproj”的操作 - 失败。
10>------ 已启动全部重新生成: 项目: benchmark_shm_channel_recv, 配置: Debug Win32 ------
10>Building Custom Rule E:/OpenSource/libatbus/tools/CMakeLists.txt
8>benchmark_io_stream_channel_recv.vcxproj -> E:\OpenSource\libatbus\vs_build\tools\Debug\benchmark_io_stream_channel_recv.exe
10>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/tools/CMakeFiles/generate.stamp is up-to-date.
10>benchmark_shm_channel_recv.cpp
9>benchmark_io_stream_channel_send.vcxproj -> E:\OpenSource\libatbus\vs_build\tools\Debug\benchmark_io_stream_channel_send.exe
11>------ 已启动全部重新生成: 项目: benchmark_shm_channel_send, 配置: Debug Win32 ------
7>atbus_test_utils.cpp
7>buffer_test.cpp
11>Building Custom Rule E:/OpenSource/libatbus/tools/CMakeLists.txt
11>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/tools/CMakeFiles/generate.stamp is up-to-date.
7>channel_io_stream_tcp_test.cpp
7>channel_io_stream_unix_test.cpp
11>benchmark_shm_channel_send.cpp
12>------ 已启动全部重新生成: 项目: show_shm_channel, 配置: Debug Win32 ------
12>Building Custom Rule E:/OpenSource/libatbus/tools/CMakeLists.txt
12>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/tools/CMakeFiles/generate.stamp is up-to-date.
7>channel_mem_test.cpp
10>benchmark_shm_channel_recv.vcxproj -> E:\OpenSource\libatbus\vs_build\tools\Debug\benchmark_shm_channel_recv.exe
12>show_shm_channel.cpp
11>benchmark_shm_channel_send.vcxproj -> E:\OpenSource\libatbus\vs_build\tools\Debug\benchmark_shm_channel_send.exe
7>atbus_unit_test.vcxproj -> E:\OpenSource\libatbus\vs_build\test\Debug\atbus_unit_test.exe
12>show_shm_channel.vcxproj -> E:\OpenSource\libatbus\vs_build\tools\Debug\show_shm_channel.exe
13>------ 已启动全部重新生成: 项目: ALL_BUILD, 配置: Debug Win32 ------
13>Building Custom Rule E:/OpenSource/libatbus/CMakeLists.txt
13>CMake does not need to re-run because E:/OpenSource/libatbus/vs_build/CMakeFiles/generate.stamp is up-to-date.
========== 全部重新生成: 成功 12 个，失败 1 个，跳过 0 个 ==========

vs2017 解决方案视图如下：
<img width="262" alt="捕获" src="https://user-images.githubusercontent.com/3354428/58077919-211dc280-7be0-11e9-8d46-60401dfd7e39.PNG">

谢谢！

**Comment by owt5008137** [comment]
@zuowanbushiwo

我目前还没有写 ```libatbus``` 和 ```libatframe_utils``` 的 vcpkg 构建脚本，因为这两个库目前还是滚动更新，还没有走release的发布方式。

但是可以在 libatbus 执行cmake的时候指定 libuv 和 msgpack 的prebuilt目录来设置使用的依赖库的位置的。(其他的可选依赖库比如curl或者openssl也一样)，比如:

```bash
mkdir -p build_jobs_$(uname -s) ;
cd build_jobs_$(uname -s) ;
cmake .. -L # 显示所有可用选项
rm -f CMakeCache.txt ;
cmake .. -DLibuv_ROOT=<where contains include/uv.h and lib(64)/libuv(_a).(lib|dll)> -DMSGPACK_ROOT=<where contains include/msgpack.hpp>
```

**Comment by zuowanbushiwo** [comment]
@owt5008137 我用VS2017编译总是报错。
![image](https://user-images.githubusercontent.com/3354428/58080199-4cef7700-7be5-11e9-9134-cf2dd33221aa.png)
我打印变量：
message("YangDebug2  ${SAMPLE_SRC_BIN_NAME}  ${PROJECT_LIB_LINK}  ${3RD_PARTY_LIBUV_LINK_NAME}  ${3RD_PARTY_ATFRAME_UTILS_LINK_NAME}")
输出：
YangDebug2  atbus_sample_usage_01  atbus  E:/OpenSource/vcpkg/installed/x86-windows/debug/lib/libuv.lib  atframe_utils
是不是库的位置没有连接对？
从上面那个comment看，我的配置是对的，找到了libuv和msgpack。
感谢你的详细回复，谢谢！

**Comment by owt5008137** [comment]
@zuowanbushiwo 这是MSVC不支持 UTF-8 without BOM 导致的。临时性的解决方法可以不编译sample或者把 sample/atbus_sample_usage_01.cpp 另存为UTF-8 with BOM编码。我后续会修复这个问题，多谢反馈。

**Comment by zuowanbushiwo** [comment]
@owt5008137 真厉害，已经解决了。能问一下你从哪里看出是这个原因的？有相关的链接吗？我开始一直对比tools,test和sample的CMakeLists 文件，以为是这里出问题了。 感谢！

**Comment by owt5008137** [comment]
@zuowanbushiwo 
```bash
6>E:\OpenSource\libatbus\sample\sample_usage_01.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
```
这一行

**Comment by zuowanbushiwo** [comment]
感谢！
