### ISSUE TITLE
parent node居然是child node的child node, 我是哪里用的不对吗？

### ISSUE THREAD

**Issue by weinvest** [atframework/libatbus#4]
CASE_TEST(atbus_endpoint, is_child1)
{
    atbus::node::conf_t p_conf;
    atbus::node::default_conf(&p_conf);
    p_conf.children_mask = 16;

    atbus::node::conf_t c_conf;
    atbus::node::default_conf(&c_conf);
    c_conf.children_mask = 8;
    {
        atbus::node::ptr_t p_node = atbus::node::create();
        p_node->init(0x12345678, &p_conf);

        atbus::node::ptr_t c_node = atbus::node::create();
        c_node->init(0x12345679, &c_conf);
        
        CASE_EXPECT_TRUE(p_node->is_child_node(c_node->get_id()));
        
        CASE_EXPECT_FALSE(c_node->is_child_node(p_node->get_id()));
    }
}

**Comment by owt5008137** [comment]
@weinvest 这个会注册失败的，因为两个的 ```children_mask``` 。这个配置两个节点的子节点范围是 0x12345678/16 和 0x12345679/16 ，都是 0x12340000-0x1234FFFF 。互相注册会失败，会有失败回调。

如果需要点对点通信，可以把 ```children_mask``` 设成0，如果需要当作proxy使用，至少要 0x12345678/16 和 0x12355678/16 或者把16改小点。 这里16指ID的后16位

**Comment by weinvest** [comment]
谢谢，明白了，我刚开始学习你的这个库，写的很不错呀。

**Comment by owt5008137** [comment]
parent node去连接child node原生是没有的。其实当时写parent和child是为了连接分组。实际业务里都不需要多层的，这里只是顺便实现成了支持多层，算是一种过度设计。
但是你可以parent层监听断开事件，自己去定期主动连接child

**Comment by jswlives** [comment]
```
CASE_TEST(atbus_endpoint, is_child) {
  atbus::node::conf_t conf;
  atbus::node::default_conf(&conf);

  {
    conf.subnets.push_back(atbus::endpoint_subnet_conf(0, 16));
    conf.subnets.push_back(atbus::endpoint_subnet_conf(0x22345678, 16));

    atbus::node::ptr_t node = atbus::node::create();
    node->init(0x12345678, &conf);

    // 0值边界检测
    CASE_EXPECT_TRUE(node->is_child_node(0x12340000));
    CASE_EXPECT_TRUE(node->is_child_node(0x1234FFFF));
    CASE_EXPECT_FALSE(node->is_child_node(0x1233FFFF));
    CASE_EXPECT_FALSE(node->is_child_node(0x12350000));

    CASE_EXPECT_TRUE(node->is_child_node(0x22340000));
    CASE_EXPECT_TRUE(node->is_child_node(0x2234FFFF));
    CASE_EXPECT_FALSE(node->is_child_node(0x2233FFFF));
    CASE_EXPECT_FALSE(node->is_child_node(0x22350000));


    //测试子节点的父节点
    atbus::node::conf_t sub_conf;
    atbus::node::default_conf(&sub_conf);
    atbus::node::ptr_t sub_node = atbus::node::create();
    sub_node->init(0x12340000, &sub_conf);
    CASE_EXPECT_TRUE(sub_node->is_parent_node(0x12345678));

    // 自己是自己的子节点
    CASE_EXPECT_TRUE(node->is_child_node(node->get_id()));

    // 0值边界检测 - 静态接口
    CASE_EXPECT_TRUE(atbus::endpoint::is_child_node(0x12345678, 0x12345678, 16, 0x12340000));
    CASE_EXPECT_TRUE(atbus::endpoint::is_child_node(0x12345678, 0x12345678, 16, 0x1234FFFF));
    CASE_EXPECT_FALSE(atbus::endpoint::is_child_node(0x12345678, 0x12345678, 16, 0x1233FFFF));
    CASE_EXPECT_FALSE(atbus::endpoint::is_child_node(0x12345678, 0x12345678, 16, 0x12350000));

    // 自己是自己的子节点 - 静态接口
    CASE_EXPECT_FALSE(atbus::endpoint::is_child_node(0x12345678, 0x12345678, 16, 0x12345678));
  }
```
你好，我在你的测试用例里面加了一段代码，测试子节点的父节点，为什么判断子节点成功，翻过来子节点判断父节点却不对，想了解一下父节点的信息想怎样维护的

**Comment by owent** [comment]
atbus::node 要完成通信注册，才能确认父节点。
详见: [atbus_node_reg_test.cpp](https://github.com/atframework/libatbus/blob/9f914c2153eacc5b3895046bb488b5e67003ef34/test/case/atbus_node_reg_test.cpp#L809) 的 [928 行](https://github.com/atframework/libatbus/blob/9f914c2153eacc5b3895046bb488b5e67003ef34/test/case/atbus_node_reg_test.cpp#L928)

**Comment by jswlives** [comment]
有点明白了，所以atsf4g-co里面的gateway就是用来管理父子节点注册的是吧

**Comment by owent** [comment]
对的，atproxy主要目的是用于转发消息的，收敛连接用。会用到父子节点的注册的特性。
