### ISSUE TITLE
为啥msg_handler::on_recv_data_transfer_rsp没有处理transfer success的情况

### ISSUE THREAD

**Issue by weinvest** [atframework/libatbus#5]
int msg_handler::on_recv_data_transfer_rsp(node &n, connection *conn, protocol::msg &m, int /*status*/, int /*errcode*/) {
        if (NULL == m.body.forward || NULL == conn) {
            ATBUS_FUNC_NODE_ERROR(n, NULL == conn ? NULL : conn->get_binding(), conn, EN_ATBUS_ERR_BAD_DATA, 0);
            return EN_ATBUS_ERR_BAD_DATA;
        }

        _if (m.body.forward->to == n.get_id()) {
            ATBUS_FUNC_NODE_ERROR(n, conn->get_binding(), conn, m.head.ret, 0);
            n.on_send_data_failed(conn->get_binding(), conn, &m);
            return EN_ATBUS_ERR_SUCCESS;
        }_

**Comment by owt5008137** [comment]
因为libatbus的协议设计里，失败才会回发transfer失败的通知。成功是不通知的。这里的transfer主要是应对要做消息中转的情况。所以如果失败了可以通知上层做处理

**Comment by weinvest** [comment]
可是msg_handler::on_recv_data_transfer_req有回过success消息呀

int msg_handler::on_recv_data_transfer_req(node &n, connection *conn, protocol::msg &m, int /*status*/, int /*errcode*/) {
        if (NULL == m.body.forward || NULL == conn) {
            ATBUS_FUNC_NODE_ERROR(n, NULL == conn ? NULL : conn->get_binding(), conn, EN_ATBUS_ERR_BAD_DATA, 0);
            return EN_ATBUS_ERR_BAD_DATA;
        }

        if (m.body.forward->to == n.get_id()) {
            ATBUS_FUNC_NODE_DEBUG(n, (NULL == conn ? NULL : conn->get_binding()), conn, &m, "node recv data length = %lld",
                                  static_cast<unsigned long long>(m.body.forward->content.size));
            n.on_recv_data(conn->get_binding(), conn, m, m.body.forward->content.ptr, m.body.forward->content.size);

            if (m.body.forward->check_flag(atbus::protocol::forward_data::FLAG_REQUIRE_RSP)) {
                return **send_transfer_rsp(n, m, EN_ATBUS_ERR_SUCCESS)**;
            }
            return EN_ATBUS_ERR_SUCCESS;
        }

**Comment by owt5008137** [comment]
这里有一点是因为历史原因。最早版本里正常发送成功是没有回包的，所以回调的名字叫 ```on_send_data_failed``` ，但是有些重要消息希望能感知到对方确实收到了，所以增加了 ```FLAG_REQUIRE_RSP``` 这个选项。但是没有增加新的事件，而是在老的事件里通过判定返回码来判定是成功还是失败

**Comment by owt5008137** [comment]
我最近会抽时间优化一下 libatbus 的协议层，会有比较大的变动。同时会增加一些跨版本检测和兼容性相关的东西和一个简单的认证功能。
因为改动比较大，所以也会改掉这个命名的。

**Comment by owt5008137** [comment]
新版本已合入
