### ISSUE TITLE
全局路由表下发没有实现吗？

### ISSUE THREAD

**Issue by tangzhenquan** [atframework/libatbus#6]
在代码里看到
// TODO 防止短时间内批量上报注册协议，所以合并上报数据包
 // TODO 给所有需要全局路由表的子节点下发数据

问一下作者实现没有

**Comment by owt5008137** [comment]
@tangzhenquan 
没有，我们现在用etcd做服务治理了。所以不需要这个了

**Comment by tangzhenquan** [comment]
hi，大佬，我还有两个问题咨询一下
1. 父节点只有一个的话，单点故障怎么办？
2. 如果要向某服务通讯，必须知道某服务的bus_id,假如某服务部署了两个节点（bus_id不同，可以扩展为3个或者4个节点），也就是没办法提前得知bus_id，想通过type_name随机给某个节点通讯，在这套框架上改动大吗？

**Comment by owt5008137** [comment]
@tangzhenquan 实际的实践中父节点只是用来做proxy agent的，挂了直接拉起就好了。
https://github.com/atframework/atsf4g-co 这是个示例的使用的repo。
在这个示例里，是用的etcd做服务发现。利用libatbus简单地做一个弱状态的全局路由表实际上实时性和一致性都没有外部借一个专用的服务治理的服务好。所以我们项目实际中是用etcd的。
如果想用zookeeper也可以。

**Comment by tangzhenquan** [comment]
@owt5008137 感谢回复  我看了atsf4g-co例子，发现atproxy用了服务治理，不同机器上的atproxy互联，这样结合父子节点特性，相当于拥有了全局路由表。这样节点之间就可以愉快的通讯了。不知道这个理解有没有问题。

如果没有问题的话，我想问一下如果只知道被请求服务的type_name的话，怎么去跟这个服务通讯，在这套框架里面我能想到的是，每个服务都接入服务治理，然后通过type_name找到服务的信息，然后直联过去，但如果这样做的话，atproxy的存在貌似没有必要了,盼能指点迷津哈

**Comment by owt5008137** [comment]
@tangzhenquan 是的，就是你理解的意思。通用组件的部分有个通用的 etcd module (https://github.com/atframework/atsf4g-co/tree/master/atframework/service/component/modules) 
在配置atapp的时候添加进去就可以通过配置来控制节点上报。
配置模板在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/helper/template/etc/atapp.template.conf
生产配置的配置在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/config.conf#L95
目前支持按id、按类型、按名字（就是类型+id）和按自定义tag上报。就可以用这个来做服务发现。

atproxy的目的是按分组收敛连接。可以减少连接数，提高大规模集群的稳定性和减少资源浪费。

**Comment by tangzhenquan** [comment]
@owt5008137 谢谢解答，我再研究研究，有问题给你发邮件哈

**Comment by jswlives** [comment]
> 如果要向某服务通讯，必须知道某服务的bus_id,假如某服务部署了两个节点（bus_id不同，可以扩展为3个或者4个节点），也就是没办法提前得知bus_id，想通过type_name随机给某个节点通讯，在这套框架上改动大吗？

**Comment by jswlives** [comment]
> @tangzhenquan 实际的实践中父节点只是用来做proxy agent的，挂了直接拉起就好了。
> https://github.com/atframework/atsf4g-co 这是个示例的使用的repo。
> 在这个示例里，是用的etcd做服务发现。利用libatbus简单地做一个弱状态的全局路由表实际上实时性和一致性都没有外部借一个专用的服务治理的服务好。所以我们项目实际中是用etcd的。
> 如果想用zookeeper也可以。

这里还是很疑惑，就正如@tangzhenquan所说的，我们这边假如有个战斗服集群，客户端要创建战斗的时候不关心具体要发给哪一个战斗，只想发给随机一个战斗服，那么如何用etc来做？这个随机是在客户端有个全局路由表来随机？还是说发给atproxy，由atproxy来负责随机转发

**Comment by jswlives** [comment]
> @tangzhenquan 是的，就是你理解的意思。通用组件的部分有个通用的 etcd module (https://github.com/atframework/atsf4g-co/tree/master/atframework/service/component/modules)
> 在配置atapp的时候添加进去就可以通过配置来控制节点上报。
> 配置模板在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/helper/template/etc/atapp.template.conf
> 生产配置的配置在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/config.conf#L95
> 目前支持按id、按类型、按名字（就是类型+id）和按自定义tag上报。就可以用这个来做服务发现。
> 
> atproxy的目的是按分组收敛连接。可以减少连接数，提高大规模集群的稳定性和减少资源浪费。

按类型来上报的话，怎样往一个类型名字的服务发送消息呢，比如需要把战斗任务随机发送给一个战斗服

**Comment by owent** [comment]
> > @tangzhenquan 是的，就是你理解的意思。通用组件的部分有个通用的 etcd module (https://github.com/atframework/atsf4g-co/tree/master/atframework/service/component/modules)
> > 在配置atapp的时候添加进去就可以通过配置来控制节点上报。
> > 配置模板在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/helper/template/etc/atapp.template.conf
> > 生产配置的配置在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/config.conf#L95
> > 目前支持按id、按类型、按名字（就是类型+id）和按自定义tag上报。就可以用这个来做服务发现。
> > atproxy的目的是按分组收敛连接。可以减少连接数，提高大规模集群的稳定性和减少资源浪费。
> 
> 按类型来上报的话，怎样往一个类型名字的服务发送消息呢，比如需要把战斗任务随机发送给一个战斗服

atapp的discovery模块有一些常用的服务分发算法，随机、一致性hash等等

**Comment by jswlives** [comment]
> > > @tangzhenquan 是的，就是你理解的意思。通用组件的部分有个通用的 etcd module (https://github.com/atframework/atsf4g-co/tree/master/atframework/service/component/modules)
> > > 在配置atapp的时候添加进去就可以通过配置来控制节点上报。
> > > 配置模板在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/helper/template/etc/atapp.template.conf
> > > 生产配置的配置在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/config.conf#L95
> > > 目前支持按id、按类型、按名字（就是类型+id）和按自定义tag上报。就可以用这个来做服务发现。
> > > atproxy的目的是按分组收敛连接。可以减少连接数，提高大规模集群的稳定性和减少资源浪费。
> > 
> > 
> > 按类型来上报的话，怎样往一个类型名字的服务发送消息呢，比如需要把战斗任务随机发送给一个战斗服
> 
> atapp的discovery模块有一些常用的服务分发算法，随机、一致性hash等等

看到了，那就是说app的etcd模块里面包含着全局的路由表信息是吧

**Comment by owent** [comment]
> > > > @tangzhenquan 是的，就是你理解的意思。通用组件的部分有个通用的 etcd module (https://github.com/atframework/atsf4g-co/tree/master/atframework/service/component/modules)
> > > > 在配置atapp的时候添加进去就可以通过配置来控制节点上报。
> > > > 配置模板在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/helper/template/etc/atapp.template.conf
> > > > 生产配置的配置在： https://github.com/atframework/atsf4g-co/blob/master/install/tools/script/config.conf#L95
> > > > 目前支持按id、按类型、按名字（就是类型+id）和按自定义tag上报。就可以用这个来做服务发现。
> > > > atproxy的目的是按分组收敛连接。可以减少连接数，提高大规模集群的稳定性和减少资源浪费。
> > > 
> > > 
> > > 按类型来上报的话，怎样往一个类型名字的服务发送消息呢，比如需要把战斗任务随机发送给一个战斗服
> > 
> > 
> > atapp的discovery模块有一些常用的服务分发算法，随机、一致性hash等等
> 
> 看到了，那就是说app的etcd模块里面包含着全局的路由表信息是吧

是的
